### ISSUE TITLE
Emails with double byte characters cannot be used to get Open badge

### ISSUE THREAD

**Issue by tejasbansod** [assistx/openbadges#29]
Environment : IE 10 running on Windows 8

How Found - Microsoft New SDET Bug Bash
 Priority - 1
 Severity - 1
 Description and Customer Impact - After entering a double byte character email address on http://msobitest.azurewebsites.net/ it throws an error saying " Contact must be a valid email address if supplied "

Repro Steps : 
 1> Navigate to http://msobitest.azurewebsites.net/
 2> Enter a double byte character email address.
 3> Click "Get your open Badge".

Results: - It throws an error saying " Contact must be a valid email address if supplied "

![Test2](https://f.cloud.github.com/assets/2066618/260299/1fb48c6a-8cd3-11e2-9882-87076e104db5.JPG)

Expected : It should handle double byte character email address like it handles single byte characters.

**Comment by msousley** [comment]
While in theory RFC 6530 & 6531 allow for double-byte characters in email address, almost none of the SMTP servers out there actually support it.  They only support up to RFC 5322 which only allow ASCII a-zA-Z0-9 and a few other characters (_ . - for the most part).  As of today you can't create a double-byte email address in Facebook, Gmail/Google, Live ID (hotmail) or Yahoo.  So for now, we are not going to fix this so that only RFC 5322 address are allowed.
