### ISSUE TITLE
AW-10: Adding Child Device With ID Needs Dashes "-"

### ISSUE THREAD

**Issue by danielbae** [assistx/openbadges#352]
apParent build 171024
apParent windows app 1.0.5

Sample ID:
1234-5678-90123-123456

This must be entered as shown. The following will not do anything:
1234567890123123456

Date Found: 10/25/17

**Comment by aloh86** [comment]
I'm going to say this is by design. The ID is saved on the server with dashes, so I have to compare it against dashes anyway. I could strip out dashes locally and the value I get from the server, then do a comparison, but I think requiring the dash input helps users to verify visually what they're inputting is correct.

I will notify user that dashes are required when they input the id.
